name: ffastdb
description: A high-performance, pure-Dart embedded NoSQL database with B-Tree indexes, WAL crash recovery, and reactive queries.
version: 0.0.1
repository: https://github.com/gonojan/fastdb

environment:
  sdk: ^3.11.1

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  benchmark_harness: ^2.4.0
  glados: ^1.1.7
