// Public barrel exports — users only need: import 'package:ffastdb/ffastdb.dart';
export 'src/fastdb.dart';
export 'src/annotations.dart';
export 'src/ffastdb_singleton.dart';
export 'src/storage/storage_strategy.dart';
export 'src/storage/memory_storage_strategy.dart';
export 'src/storage/wal_storage_strategy.dart';
export 'src/storage/buffered_storage_strategy.dart';
export 'src/storage/web/web_storage_strategy.dart';
export 'src/serialization/type_adapter.dart';
export 'src/query/fast_query.dart';
export 'src/platform/open_database.dart';